### ISSUE TITLE
Error: Cannot resolve a Slate point from DOM point: [object Text]

### ISSUE THREAD

**Issue by pm0u** [davydog187/sanity-portable-table#12]
When editing a table using the default configuration, I receive this error in the studio. I am able to edit plaintext in the cell, but am unable to select any text or apply any annotations

sanity 3.12.0

**Comment by davydog187** [comment]
Thanks for the report @pm0u. Would you be interested in sending a PR?

**Comment by pm0u** [comment]
@davydog187 at this point we've worked around needing this library for our use case, but we may need it in the future so I could revisit this. I'm honestly not sure what could be causing this though. I've found a few random mentions of this issue but nothing that seems to be very related to what would be happening here. If you have any pointers I can take a closer look

**Comment by davydog187** [comment]
I don't have any further insight, sorry

**Comment by pm0u** [comment]
Just took a quick look again - this is in a monorepo, so I thought it was possible that there were some version conflicts involved. I ensured there were no duplicate versions of any dependencies, still ran into the issue with the default config.

The error I see when I click into the text area is:
```
Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
    at Object.toSlatePoint (react-editor.ts:593:13)
    at Object.toSlateRange (react-editor.ts:665:32)
    at HTMLDocument.<anonymous> (editable.tsx:350:37)
    at invokeFunc (debounce.js:95:19)
    at leadingEdge (debounce.js:105:22)
    at HTMLDocument.debounced (debounce.js:172:16)
    at invokeFunc (debounce.js:95:19)
    at trailingEdge (debounce.js:144:14)
    at timerExpired (debounce.js:132:14)
```
And then the first letter that I type produces the following:

```
Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
    at Object.toSlatePoint (react-editor.ts:593:13)
    at Object.toSlateRange (react-editor.ts:665:32)
    at HTMLDivElement.<anonymous> (editable.tsx:448:39)

Error: Cannot resolve a Slate point from DOM point: [object Text],1
    at Object.toSlatePoint (react-editor.ts:593:13)
    at Object.toSlateRange (react-editor.ts:665:32)
    at HTMLDocument.<anonymous> (editable.tsx:350:37)
    at invokeFunc (debounce.js:95:19)
    at leadingEdge (debounce.js:105:22)
    at HTMLDocument.debounced (debounce.js:172:16)
    at invokeFunc (debounce.js:95:19)
    at trailingEdge (debounce.js:144:14)
    at timerExpired (debounce.js:132:14)
 ```

**Comment by davydog187** [comment]
This is likely a Sanity bug and not something that can be fixed in this repo.

**Comment by chinssiang** [comment]
I got the same issue with the following error message 

```
Unhandled Runtime Error
Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0

Call Stack
Object.toSlatePoint
node_modules/@sanity/slate-react/dist/index.es.js (3049:0)
Object.toSlateRange
node_modules/@sanity/slate-react/dist/index.es.js (3106:0)
HTMLDocument.eval
node_modules/@sanity/slate-react/dist/index.es.js (1234:0)
invokeFunc
node_modules/lodash/debounce.js (95:0)
leadingEdge
node_modules/lodash/debounce.js (105:0)
HTMLDocument.debounced
node_modules/lodash/debounce.js (172:0)
invokeFunc
node_modules/lodash/debounce.js (95:0)
trailingEdge
node_modules/lodash/debounce.js (144:0)
timerExpired
node_modules/lodash/debounce.js (132:0)
```

I'm using Sanity embedding studio with NextJS
Sanity: "^3.15.1"

**Comment by davydog187** [comment]
Sorry but I dont have time to address this issue. PRs are welcome

**Comment by alexgorgos** [comment]
add

renderBlock={props.renderBlock} renderAnnotation={props.renderAnnotation}

props in TableInput.tsx for the MemberField component.

{rowsMember && ( <MemberField member={rowsMember} renderInput={rowsInput} renderField={props.renderField} renderItem={props.renderItem} renderPreview={props.renderPreview} renderBlock={props.renderBlock} renderAnnotation={props.renderAnnotation} /> )}

That should fix it

**Comment by alexgorgos** [comment]
add
```
renderBlock={props.renderBlock}
renderAnnotation={props.renderAnnotation}
```

props in TableInput.tsx for the MemberField component.
```
{rowsMember && (
	<MemberField
		member={rowsMember}
		renderInput={rowsInput}
		renderField={props.renderField}
		renderItem={props.renderItem}
		renderPreview={props.renderPreview}
		renderBlock={props.renderBlock}
		renderAnnotation={props.renderAnnotation}
	/>
)}
```
That should fix it
